### PR TITLE
admin_check

### PR DESCRIPTION
**Pull request by Rxann**
This pr adds an admin_check translation.

Once this gets merged, I will implement the translation and open a pr on the main repo.

### CODE REVIEW

**Comment by Yimura** [comment]
Before I take a look at this PR could you revert the line endings back to what they are?

**Comment by Rxann** [comment]
Yeah, I will work on this.

**Comment by Rxann** [comment]
@Yimura does this fix the things you requested?

**Comment by Rxann** [comment]
> > @Yimura does this fix the things you requested?
> 
> 
> 
> You seem to have also changed the indentation of the whole file for some reason.

Can i revert my changes to basically start over?

**Pull request closed without merging**
