### PR TITLE
Updated DE

### PR DESCRIPTION
**Pull request by Sencaid**

### CODE REVIEW

**Comment by gir489returns** [comment]
BACKEND_LOOPED_HUD_TRANSITION_STATE_WAIT_FOR_SUMMON has a spelling mistake, Beschörung should be Beschwörung. You also need to increment the version number in the index JSON file. I tried to do it myself and push it, but you must've disabled write access to YimMenu devs to the PR repo.

**Comment by Sencaid** [comment]
> BACKEND_LOOPED_HUD_TRANSITION_STATE_WAIT_FOR_SUMMON has a spelling mistake, Beschörung should be Beschwörung. You also need to increment the version number in the index JSON file. I tried to do it myself and push it, but you must've disabled write access to YimMenu devs to the PR repo.

Oh, thanks for the notice, i change it real quick

**Comment by Sencaid** [comment]
@gir489returns Why do I need to increase the version number? My index file isn't being merged anyway and its synced, it salready 124. You can no edits stuff

**Comment by gir489returns** [comment]
> @gir489returns Why do I need to increase the version number? My index file isn't being merged anyway and its synced, its already 124. You can now edit stuff

YimMenu locally stores the version number you have from pulling Index.json each time on boot. If it detects the version number you have is < the version number from index, it will update the local translations.

**Comment by Sencaid** [comment]
@gir489returns This means, i increase it to 125 and also include it in my pull request?

**Comment by gir489returns** [comment]
> @gir489returns This means, i increase it to 125 and also include it in my pull request?

Yes.

**Review by gir489returns — APPROVED** [review]

**Comment by Sencaid** [comment]
@gir489returns bruh i was just about to fix the type issue. Its still Beschörung now

**Pull request merged**
