### PR TITLE
Flying Axe Translation

### PR DESCRIPTION
**Pull request by Rxann**

### CODE REVIEW

**Review by rkwapisz — COMMENTED** [review]
You should move BACKEND_LOOPED_FLYING_AXE just before BACKEND_LOOPED_HUD_TRANSITION_STATE_CANCEL_JOINING to maintain alphabetical order.

**Comment by rkwapisz** [comment]
You can also add a translation for "BACKEND_LOOPED_FLYING_AXE_DESC".

I personally like "Summons a deadly swirling axe around you that causes chaos and destruction."

`  "BACKEND_LOOPED_FLYING_AXE_DESC": "Summons a deadly swirling axe around you that causes chaos and destruction.",`

**Review by Yimura — CHANGES_REQUESTED** [review]
Missing `BACKEND_LOOPED_FLYING_AXE_DESC` and see comments from @rkwapisz.

**Comment by Rxann** [comment]
@rkwapisz thank you for the assistance with the translations. 

@Yimura i have added a translation for #2973 where the player pointer is null. I will open a pr on YimMenu once this is merged.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
