### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by Baicha12138**

### CODE REVIEW

**Comment by Yimura** [comment]
Seems someone made a PR on your repository, would you mind taking a look at merging that first before I merge your PR?
https://github.com/Baicha12138/Translations/pull/1

**Comment by Baicha12138** [comment]
> Seems someone made a PR on your repository, would you mind taking a look at merging that first before I merge your PR? [Baicha12138#1](https://github.com/Baicha12138/Translations/pull/1)

sure

**Comment by Yimura** [comment]
Yeah I'm waiting a bit longer before merging, I'm still working on porting everything to translation keys

**Review by Yimura — APPROVED** [review]
Looks good, @Aure7138 had a look.

Thanks for your contribution.

**Pull request merged**
