### PR TITLE
Created pl_PL.json

### PR DESCRIPTION
**Pull request by heni015**
#2 First translation
There may be some incorrect translations, depending on the purpose of the function, but I tried my best. I use this version myself, so I will make corrections when I find the need.

### CODE REVIEW

**Comment by gir489returns** [comment]
> I tried my best.

That's all we ask, really. I personally did the Russian translation and know the hardship of trying to translate a westernized language in an eastern language, especially where we use so much GTA slang to the point we have to just keep it as-is in the translation. We're not aiming for perfection; we're aiming for readability. The menu in its current state has a very steep learning curve, and pieces make very little or no sense at all to someone who's never hacked a game in their life. The goal of the translations is to at least bridge some of the gap for those people who can't even speak English.

**Comment by gir489returns** [comment]
I'm not sure how you tested this, since the file submitted contained 3 JSON parsing issues, where you used an open curly bracket instead of a comma, but I'll take your word that this was translated by hand and not by machine.

**Review by gir489returns — APPROVED** [review]

**Comment by heni015** [comment]
Sometimes I had to use google translate cuz I was missing a word or an appropriate replacement, and I knew what it was about so I had to look for a replacement word, but for example CNetGamePlayer or other similar ones I didn't translate. Sometimes I fell asleep while explaining this ^^ and I didn't test it, now I checked it in Validator :x
As a result, Notepad++ formatting showing me crashed on the correct lines... Like in en_EN.json: 
`1949  "VIEW_WORLD_INCLUDE": "Include:",` or few others, but they work fine.
Thank you for the corrections

**Comment by heni015** [comment]
I cannot find an equivalent for the "Vehicles" tab: checkbox responsible for "Vehicle controller".
In the English language file it is there, but responsible for other functions, namely those relating to the player selected from the list and his vehicle.
I think it's last correction to do.

**Comment by rkwapisz** [comment]
> I cannot find an equivalent for the "Vehicles" tab: checkbox responsible for "Vehicle controller". In the English language file it is there, but responsible for other functions, namely those relating to the player selected from the list and his vehicle. I think it's last correction to do.
> 
> @edit image The only line we can find for "Enables" is 869: "ORBITAL_DRONE_DESC": "Enables/Disables the orbital drone",

This is a defect in line 37 of vehicle_control_service.cpp where the string is hardcoded:
vehicle_control_command g_vehicle_control("vehiclecontrol", "Vehicle controller", "Enables/Disables the vehicle controller.",

A fix will be issued shortly, then the feature will access the translation file.

**Comment by Yimura** [comment]
@heni015, you should now be able to add the vehicle controller to the translation file.

**Comment by heni015** [comment]
Added:
```
  "VEHICLE_INFINITE_AMMO"
  "VEHICLE_INFINITE_AMMO_DESC"
  "ENABLE_BOTH_MK1_AND_MK2_VARIANTS"
  "ENABLE_BOTH_MK1_AND_MK2_VARIANTS_DESC"
  "VIEW_GUI_FORMAT_MONEY"
```
but my question is, why in a "Personal" TAB settings of "Weapons" is function about MK1 and MK2, put in in "Vehicle" TAB maybe? :D

**Review by Yimura — DISMISSED** [review]

**Pull request merged**
