### PR TITLE
[de_DE] Deutsch/German translations

### PR DESCRIPTION
**Pull request by pierrelasse**
Just saw this https://github.com/YimMenu/Translations/pull/25 after i already finished this....

### CODE REVIEW

**Comment by pierrelasse** [comment]
It would be good if you could load a language file for testing.

**Comment by Yimura** [comment]
Yeah don't worry because the guy from #25 never bothered finishing them and they're most likely outdated.

**Comment by pierrelasse** [comment]
Damn, what a fast reply

**Comment by gir489returns** [comment]
I am working on a Russian translation, and a lot of the translations I’m finding are deprecated or straight up just not used. We should merge our notes on these and remove them from the EN file when we’re done. So far all I’ve found is ASCENDING is removed, but I remember removing like 5-6 lines from another translation PR I made before. It would be a super pain in the ass to search the code and check each of the 1000 lines of translation, but if I run into one I can’t quite translate I check if it’s in the code still and if not I just give it the fuck it adjustment.

**Comment by xiaoxiao921** [comment]
Checking for unused translation should be quite easy actually, as we can just write a small script that check every files from YimMenu and scan strings that end with `_T`

**Comment by pierrelasse** [comment]
> Checking for unused translation should be quite easy actually, as we can just write a small script that check every files from YimMenu and scan strings that end with `_T`

I can try do that later

**Comment by pierrelasse** [comment]
We have a problem... I can exclude all keys that start with a "REQUEST_" tho this is meh
image

**Comment by pierrelasse** [comment]
> Or just do the inverse load in all the keys, then search for each key individually through the source code. Then you'll catch 100% of the unused keys.
> 
> And to be fair we could probably make a Github action that just checks this every month or so on the code base to see which keys can be retired and maybe open a PR removing all those keys from the translations repository.

Inverse load? The problem is that for example "GUI_SOMETHING" will never be in the code like this. There will be only "GUI_" and "SOMETHING" in the code.

**Comment by Yimura** [comment]
That's fine we can implement edge cases for that easily.

**Comment by Yimura** [comment]
According to my testing I got the following deprecated translation keys:

<details>
  <summary>Deprecated Keys</summary>
  
```json
[
    "ADVERTISE_YIMMENU_DESC",
    "ADVERTISE_YIMMENU",
    "ASCENDING",
    "AUTO_TP_TO_WP",
    "BYPASS_C4_LIM",
    "CAMHEDZ",
    "CHECKPOINTS",
    "DEBUG_GLOBAL_FREEZE_TOGGLE",
    "DEBUG_GLOBAL_FREEZE",
    "DEBUG_GLOBAL_OFFSET_COUNT",
    "DEBUG_GLOBALS_ADD",
    "DEBUG_GLOBALS_BASE_ADDRESS",
    "DEBUG_GLOBALS_ENABLE_FREEZING",
    "DEBUG_GLOBALS_NAME",
    "DEBUG_GLOBALS_NEW",
    "DEBUG_GLOBALS_VALUE",
    "DECLOAK",
    "DESCENDING",
    "DISABLE_FILTER",
    "DMG_MULTIPLR",
    "ERROR_INVALID_VEHICLE",
    "ERROR_NO_OBJECTIVE",
    "ERROR_NO_SEATS_FREE",
    "ERROR_NO_WAYPOINT_SET",
    "ERROR_PLAYER_IS_DEAD",
    "EVENT_STARTER",
    "FAKE_DEPOSIT",
    "GUI_TAB_CONTEXT_MENU",
    "GUI_TAB_ESP",
    "GUI_TAB_GUI",
    "GUI_TAB_IPL",
    "GUI_TAB_NEARBY",
    "GUI_TAB_ORBITAL_DRONE",
    "GUI_TAB_PERSIST_CAR",
    "GUI_TAB_PERSONAL_VEHICLE",
    "GUI_TAB_SESSION",
    "GUI_TAB_TIME_N_WEATHER",
    "GUI_TAB_TRANSLATION",
    "GUI_TAB_WATER",
    "GUNSLINGER",
    "HIJACK_TRAIN_DELETED_TRAIN",
    "HOST_TARGET",
    "IMPROMPTU_RACE",
    "INPUT_RID",
    "IP_ADDRESS_COLON",
    "IP_ADDRESS",
    "KICK_BY_RID",
    "KICK_BY_USERNAME",
    "LEFT_SIDED",
    "LESSEN_BREAKUP_KICK_DESCRIPTION",
    "LESSEN_BREAKUP_KICK",
    "LOCAL_CPED",
    "LOCAL_WEATHER",
    "ONE_ON_ON_DM",
    "OVERRIDE_TIME",
    "PART_WATER_DESC",
    "PART_WATER",
    "PLAYER_INFO_ID",
    "PLAYER_INFO_SESSION_HOST",
    "PLAYER_OPTIONS",
    "PLAYER_SPOOFED_NAME",
    "REGION_SWITCHER",
    "REMOTE_CRASH_INVALID_BLACKLIST_FROM",
    "REMOTE_CRASH_INVALID_BLACKLIST",
    "REMOTE_CRASH_INVALID_TRANSITION_FROM",
    "REMOTE_CRASH_INVALID_TRANSITION",
    "REMOTE_KICK_BREAKUP_PLAYER",
    "REMOTE_KICK_BREAKUP",
    "REMOTE_KICK_GAMER_INSTRUCTION",
    "REMOTE_KICK_LOST_CONNECTION_PLAYER",
    "REMOTE_KICK_LOST_CONNECTION",
    "REMOTE_NAME_SPOOFING",
    "ROCKSTAR_ID_COLON",
    "SETTINGS_UI_SCALE_DESCRIPTION",
    "SPACE_MONKEY",
    "SPOOF_PLAYER_NAMES_DESC",
    "SPOOF_PLAYER_NAMES",
    "SPOOFING_DESCRIPTION",
    "SPOOFING_EXTRA",
    "SPOOFING_IP_DESCRIPTION",
    "SPOOFING_IP",
    "SPOOFING_IS_CHEATER",
    "SPOOFING_IS_DEV",
    "SPOOFING_IS_QA",
    "SPOOFING_ROCKSTAR_ID",
    "SPOOFING_USERNAME_LOCAL",
    "SPOOFING_USERNAME",
    "TELEPORTS",
    "TP_TO_CAYO_DESC",
    "TP_TO_CAYO",
    "TUTORIAL_DESC",
    "USERNAME_COLON",
    "VIEW_PLAYER_PLAYER_OPTIONS",
    "WIZARD"
]
```
</details>

<details>
  <summary>Code Used</summary>
  

```javascript
import fs from "fs";

/**
 * @param {string} directory The root directory to recursively grab files from.
 * @param {string[]} extensions The extensions to include
 */
const grabSourceFiles = (directory, extensions) => {
    if (!directory.endsWith('/'))
        directory += '/';

    const files = fs.readdirSync(directory);
    let collectedFiles = [];
    for (const file of files)
    {
        if (file.includes('.') && extensions.includes(file.split('.').slice(-1)[0]))
        {
            collectedFiles.push(directory + file);
        }

        if (fs.lstatSync(directory + file).isDirectory())
        {
            collectedFiles = collectedFiles.concat(grabSourceFiles(directory + file, extensions));
        }
    }

    return collectedFiles;
};

/**
 * @param {string[]} files Files to preload the contents of
 * @returns {string[]} File contents
 */
const preloadFileContents = (files) => {
    const preloadedFiles = [];
    for (const file of files) {
        preloadedFiles.push(fs.readFileSync(file, 'utf-8'));
    }
    return preloadedFiles;
}

/**
 * @param {string[]} fileContents Source file contents to check against
 * @param {string} str String to check if it exist
 */
const doesStrExistInSource = (fileContents, str) => {
    for (const contents of fileContents)
    {
        if (str.startsWith("GUI_TAB_"))
        {
            str = `TAB_DECL(${str.replace('GUI_TAB_', '')})`;
        }
        if (contents.includes(str))
        {
            return true;
        }
    }

    return false;
}

const sourceFiles = grabSourceFiles('./src/src', [ 'cpp', 'hpp' ]);
console.log(`Collected ${sourceFiles.length} source files.`);
const preloadedFiles = preloadFileContents(sourceFiles);
console.log("Finished preloading files into memory.");

const json = JSON.parse(fs.readFileSync('./data/en_US.json', 'utf-8'));
const translationKeys = Object.keys(json);
console.log(`Loaded ${translationKeys.length} from en_US.json.`);

/**
 * @type {string[]}
 */
let deprecatedStrs = [];
for (const key of translationKeys)
{
    if (!doesStrExistInSource(preloadedFiles, key))
    {
        deprecatedStrs.push(key);
    }
}
console.log(`Finished checking for deprecated keys, found ${deprecatedStrs.length} deprecated keys.`);
console.log(`Deprecation percentage of ${(deprecatedStrs.length / translationKeys.length * 100).toFixed(2)}%`);

console.log("Dumping deprecated keys...");
fs.writeFileSync('./data/deprecate.json', JSON.stringify(deprecatedStrs, null, 4));
```
</details>

**Comment by pierrelasse** [comment]
@Yimura, sre you very sure about this? So should i remove these keys or only those who dont have a _ in it?

**Comment by Yimura** [comment]
Leave it like it is currently we can always remove them later, try to match the current en_US.

**Comment by pierrelasse** [comment]
> Leave it like it is currently we can always remove them later, try to match the current en_US.

Okay, i will do that later when im on the pc

**Comment by pierrelasse** [comment]
Ok, so it should "match" now and should be ready.

**Comment by pierrelasse** [comment]
How's it going? Are there any problems or for what are we waiting?

**Comment by DayibBaba** [comment]
lgtm

**Review by Yimura — APPROVED** [review]

**Review by Yimura — APPROVED** [review]

**Review by Yimura — APPROVED** [review]

**Pull request merged**
