### PR TITLE
feat: Add translation for #2331 and update Chinese localization files

### PR DESCRIPTION
**Pull request by sch-lda**

### CODE REVIEW

**Comment by sch-lda** [comment]
image
image
In LSC, MOD means 模组/改装. In player info, MOD means 作弊者. But they share the same translation key in json. Confusing translations...

**Comment by gir489returns** [comment]
I tried to reduce value reduplication as much as possible. Adding a new key entry into the translations for the same thing in English I think is fine, just having a use case and need for it seemed better than literally assigning every translation text a key. .

**Comment by sch-lda** [comment]
Still needs polish. Some errors remain to be discovered.

**Comment by sch-lda** [comment]
Close to perfect, waiting for https://github.com/YimMenu/YimMenu/issues/2325 to be fixed before further modification and testing.

**Comment by gir489returns** [comment]
@sch-lda What's the status of this? This is holding up my Russian translation update.

**Comment by sch-lda** [comment]
> @sch-lda What's the status of this? This is holding up my Russian translation update.

I don't know when #2331 will be merged.You can do your job, if your pull request can be merged soon, I'll resolve the conflict based on your changes.

**Comment by sch-lda** [comment]
All done

**Comment by sch-lda** [comment]
Currently, no more issues can be found. If there are any minor problems, let's wait for them to be discovered and fixed in the future.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
