### PR TITLE
"Vehicle God Mode" -> "VEH GOD" style

### PR DESCRIPTION
**Pull request by pierrelasse**
I tried to change the style for vehicle godmode in esp to "VEH GOD".
I also formatted json files and remove trailing whitespaces.

This PR is related to PR https://github.com/YimMenu/YimMenu/pull/3123

### CODE REVIEW

**Review by Yimura — CHANGES_REQUESTED** [review]
Unsure if it's a good idea to go and change the translations for languages you might not be fluent in.

Instead of causing confusion for other languages by trying to translate their language it may be better to just remove the translation keys from their language so that when the translation service tries to fetch the key it falls back to the English variant making it obvious to the people that maintain those languages to open up a PR.

Reverting the changes to their languages will keep the original translation but may not fit in the context of the UI.

**Comment by gir489returns** [comment]
image

@Yimura Nothing for me to review, that I can see.

**Comment by pierrelasse** [comment]
Should I remove the translation keys or keep them? The changes a very minor and should be still readable and understandable in that language. Like `Véhicule invincible` to `VÉH GOD`.

**Comment by gir489returns** [comment]
> Should I remove the translation keys or keep them? The changes a very minor and should be still readable and understandable in that language. Like `Véhicule invincible` to `VÉH GOD`.

Your Polish change at least makes no sense. TRYB means MODE. BOGA means GOD and pojazdu means vehicle. Whoever translated it, did a literal translation of MODE GOD VEHICLE. I don't know if that's syntaxically correct in Polish, but you removed pojazdu which now makes it just say MODE GOD (God Mode). I would revert the changes to languages you do not understand. Especially pl_PL and ru_RU as whatever changes you did are not required.

**Comment by Yimura** [comment]
IMO, I'd just delete the keys from the other languages to make it obvious.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
